### ISSUE TITLE
Segfault while tracing a (long running) ci job

### ISSUE THREAD

**Issue by twouters** [zaquestion/lab#251]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e76a0]

goroutine 1 [running]:
io/ioutil.readAll.func1(0xc0000e19f0)
	/usr/lib/go/src/io/ioutil/ioutil.go:30 +0x105
panic(0x95f340, 0xe3a190)
	/usr/lib/go/src/runtime/panic.go:513 +0x1b9
bytes.(*Buffer).ReadFrom(0xc00012a0e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bytes/buffer.go:206 +0x80
io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/ioutil/ioutil.go:36 +0xb5
io/ioutil.ReadAll(0x0, 0x0, 0xc0001e40a9, 0x6, 0xc0002a1a85, 0x3, 0x0)
	/usr/lib/go/src/io/ioutil/ioutil.go:45 +0x3e
github.com/zaquestion/lab/cmd.doTrace(0xa943a0, 0xc000094020, 0xa8fe20, 0xc000096008, 0x928160, 0xc0002a07f0, 0xc0001e40a9, 0x6, 0xc0002a1a85, 0x3, ...)
	/home/twouters/.cache/pacaur/lab/src/go/src/github.com/zaquestion/lab/cmd/ci_trace.go:96 +0x31d
github.com/zaquestion/lab/cmd.glob..func4(0xe42260, 0xe6dbc8, 0x0, 0x0)
	/home/twouters/.cache/pacaur/lab/src/go/src/github.com/zaquestion/lab/cmd/ci_trace.go:61 +0x299
github.com/zaquestion/lab/vendor/github.com/spf13/cobra.(*Command).execute(0xe42260, 0xe6dbc8, 0x0, 0x0, 0xe42260, 0xe6dbc8)
	/home/twouters/.cache/pacaur/lab/src/go/src/github.com/zaquestion/lab/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/zaquestion/lab/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe46740, 0xe42260, 0xe6dbc8, 0xc000096598)
	/home/twouters/.cache/pacaur/lab/src/go/src/github.com/zaquestion/lab/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/zaquestion/lab/vendor/github.com/spf13/cobra.(*Command).Execute(0xe46740, 0xc00008c070, 0x2)
	/home/twouters/.cache/pacaur/lab/src/go/src/github.com/zaquestion/lab/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/zaquestion/lab/cmd.Execute()
	/home/twouters/.cache/pacaur/lab/src/go/src/github.com/zaquestion/lab/cmd/root.go:235 +0x187
main.main()
	/home/twouters/.cache/pacaur/lab/src/go/src/github.com/zaquestion/lab/main.go:109 +0x5e
```

**Comment by zaquestion** [comment]
I suspect this will be fixed by https://github.com/zaquestion/lab/pull/286
