### ISSUE TITLE
snippet browse panics

### ISSUE THREAD

**Issue by torkelrogstad** [zaquestion/lab#351]
Trying to browse a snippet does not work. This is on current master. 

```bash
$ lab snippet browse 1917455
panic: interface conversion: interface {} is map[string]interface {}, not []map[string]interface {}

goroutine 1 [running]:
github.com/zaquestion/lab/cmd.glob..func39(0xf06b00, 0xc00036a4b0, 0x1, 0x1)
        /home/torkel/dev/go-lang/lab/cmd/snippet_browse.go:26 +0x556
github.com/spf13/cobra.(*Command).execute(0xf06b00, 0xc00036a450, 0x1, 0x1, 0xf06b00, 0xc00036a450)
        /home/torkel/dev/go-lang/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:769 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xf07a00, 0xc0000200d0, 0x3, 0x3)
        /home/torkel/dev/go-lang/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:855 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /home/torkel/dev/go-lang/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:803
github.com/zaquestion/lab/cmd.Execute()
        /home/torkel/dev/go-lang/lab/cmd/root.go:302 +0x1e9
main.main()
        /home/torkel/dev/go-lang/lab/main.go:125 +0x80
```

I added a `fmt.Println` of `viper.AllSettings(): `map[core:map[user:torkelrogstad]]`.

**Comment by zaquestion** [comment]
I've seen this before, it has to do with how the config gets loaded by viper for hcl files, I had thought I fixed it in the `snippet browse` logic before but it seems not. https://github.com/zaquestion/lab/pull/353 should fix the issue.
