### ISSUE TITLE
lab commit b0b8ee22492b ("alec/multiple-assignees") causes panic with 'lab mr show' command

### ISSUE THREAD

**Issue by prarit** [zaquestion/lab#389]
I am using lab top-of-tree commit 236a3683336a ("Merge pull request #383 from jwessel/master").  I am testing on https://gitlab.com/prarit/sst-test.git.

I am executing 'lab mr show 1' which results in the following panic:

[prarit@prarit sst-test]$ ~/git-kernel/github/lab/lab mr show 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4d2587]

goroutine 1 [running]:
cmd.printMR
	/home/prarit/git-kernel/github/lab/cmd/mr_show.go:50
cmd.func30
	/home/prarit/git-kernel/github/lab/cmd/mr_show.go:37
github.x2ecom..z2fspf13..z2fcobra.Command.execute
	/home/prarit/go/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:769
github.x2ecom..z2fspf13..z2fcobra.Command.ExecuteC
	/home/prarit/go/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:855
github.x2ecom..z2fspf13..z2fcobra.Command.Execute
	/home/prarit/go/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:803
github.x2ecom..z2fzaquestion..z2flab..z2fcmd.Execute
	/home/prarit/git-kernel/github/lab/cmd/root.go:319
main.main
	/home/prarit/git-kernel/github/lab/main.go:196

This panic has 100% reproducibility.

git-bisect points to b0b8ee22492b ("alec/multiple-assignees").

**Comment by prarit** [comment]
@alecbz ... ping.

**Comment by prarit** [comment]
@alecbz, I apologize for the early morning issue ;).  I haven't had much time to debug and will dig in unless you beat me to it :)

P.

**Comment by prarit** [comment]
git-bisect log:

[prarit@prarit lab]$ git bisect log
git bisect start
# bad: [236a3683336a9638286cdb060ba2a54b710e0367] Merge pull request #383 from jwessel/master
git bisect bad 236a3683336a9638286cdb060ba2a54b710e0367
# good: [a7646da14338df8cdaabc2a9f80c45d47c2bd322] Merge pull request #359 from zaquestion/tls_skip_fix
git bisect good a7646da14338df8cdaabc2a9f80c45d47c2bd322
# good: [ea586a46f932d6a09369ed91d52d21ff41fa7957] Merge branch 'master' into ci-status
git bisect good ea586a46f932d6a09369ed91d52d21ff41fa7957
# good: [ea586a46f932d6a09369ed91d52d21ff41fa7957] Merge branch 'master' into ci-status
git bisect good ea586a46f932d6a09369ed91d52d21ff41fa7957
# bad: [3082619a8003b1de81a317faa82eb6fb2d5dcfd5] Merge pull request #384 from jwessel/readme_fix
git bisect bad 3082619a8003b1de81a317faa82eb6fb2d5dcfd5
# bad: [0d9ac83f660d1ebf78ccaa80427013ef3be8f6bb] Merge pull request #372 from AlecBenzer/alec/multiple-assignees
git bisect bad 0d9ac83f660d1ebf78ccaa80427013ef3be8f6bb
# good: [da7485d8933331d38baa0b96c1bc99aaf030494b] Merge pull request #361 from claytonrcarter/ci-status
git bisect good da7485d8933331d38baa0b96c1bc99aaf030494b
# good: [da7485d8933331d38baa0b96c1bc99aaf030494b] Merge pull request #361 from claytonrcarter/ci-status
git bisect good da7485d8933331d38baa0b96c1bc99aaf030494b
# bad: [b0b8ee22492b01cb8ea0b780afd66a643598c47d] alec/multiple-assignees
git bisect bad b0b8ee22492b01cb8ea0b780afd66a643598c47d
# first bad commit: [b0b8ee22492b01cb8ea0b780afd66a643598c47d] alec/multiple-assignees
